### PR TITLE
Allow extension by making members protected

### PR DESCRIPTION
**Pull request by tuimz**
This allows users to extend the GoogleAnalytics class and a custom tracking code (Per user configuration for example)

### CODE REVIEW

**Comment by justb81** [comment]
LGTM

**Comment by justb81** [comment]
@tuimz could you explain your usecase, the variable is filled by the constructor, so you could overload it there and don't need access to the property itself.

**Comment by tuimz** [comment]
Currently in my PageController class I have to following code to set an analytics account per team

    //Simplified for example
    $team = Team::first();
    config(['analytics.configurations.GoogleAnalytics.tracking_id' => $team->analyticsId]);

What seems to be better then setting a config value at runtime would be:

    //Simplified for example
    $team = Team::first();
    Analytics::setTrackingId($team->analyticsId);

I understand the constructor overloading solution, however that would involve duplicating pretty much all the code in the AnalyticsServiceProvider class as that is where it is instanciated.

**Comment by justb81** [comment]
update to version 1.4.0

thx for the PR!!!

**Comment by tuimz** [comment]
Thanks for merging!

**Pull request merged**
