### PR TITLE
Add null defaults to NoAnalytics provider

### PR DESCRIPTION
**Pull request by DougSisk**
Fixes an issue where a missing argument exception is thrown if a value
is not passed while using the NoAnalytics provider.

### CODE REVIEW

**Comment by rokde** [comment]
Your changes does not follow the interface.

**Comment by DougSisk** [comment]
So do I need to add them on to the interface? This is a bug
regardless The GoogleAnalytics interface allows null values and it's
causing some major headaches on testing environments where I don't use
track Analytics.

**Comment by rokde** [comment]
You can set null values to the method on test...but the interfaces requires a value...it makes no sense tracking a page without giving a page.

**Comment by DougSisk** [comment]
I’m talking about the trackEvent method.

**Comment by DougSisk** [comment]
Also, the `trackPage` method on the GoogleAnalytics provider has a default null value.

**Comment by rokde** [comment]
Ah, now I see what you mean. This is wrong too... I have to fix that soon.

**Comment by DougSisk** [comment]
I just committed making `$page` required.

**Pull request closed without merging**
